FROM tomcat:9-jre17 as dev_base
RUN apt-get update
RUN apt-get upgrade -y
RUN mkdir /opt/faction

# Fix issue with sending emails
RUN sed -i 's/^jdk.tls.disabledAlgorithms/# jdk.tls.disabledAlgorithms/' /opt/java/openjdk/conf/security/java.security

# Remove default Tomcat webapps
RUN rm -rf /usr/local/tomcat/webapps/manager
RUN rm -rf /usr/local/tomcat/webapps/host-manager
RUN rm -rf /usr/local/tomcat/webapps/docs
RUN rm -rf /usr/local/tomcat/webapps/examples
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Create the ROOT directory where we'll mount the exploded WAR
RUN mkdir -p /usr/local/tomcat/webapps/ROOT

# Enable context reloading by creating a context.xml for ROOT app
RUN mkdir -p /usr/local/tomcat/conf/Catalina/localhost
RUN echo '<?xml version="1.0" encoding="UTF-8"?>' > /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml && \
    echo '<Context reloadable="true">' >> /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml && \
    echo '</Context>' >> /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml

EXPOSE 8080/tcp
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
