package com.fuse.dao;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.Test;

public class FinalReportVariantTest {

    // --- Identity ---

    @Test
    public void testIdAutoGenerated() {
        FinalReportVariant v = new FinalReportVariant();
        assertNotNull("ID should be auto-generated", v.getId());
        assertFalse("ID should not be empty", v.getId().isEmpty());
    }

    @Test
    public void testIdsAreUniquePerInstance() {
        FinalReportVariant v1 = new FinalReportVariant();
        FinalReportVariant v2 = new FinalReportVariant();
        assertNotEquals("Each instance should get a unique ID", v1.getId(), v2.getId());
    }

    // --- Lombok-generated accessors (fileType, largeFile, parts) ---

    @Test
    public void testFileTypeGetterSetter() {
        FinalReportVariant v = new FinalReportVariant();
        v.setFileType("pdf");
        assertEquals("pdf", v.getFileType());
        v.setFileType("docx");
        assertEquals("docx", v.getFileType());
    }

    @Test
    public void testLargeFileFalseByDefault() {
        FinalReportVariant v = new FinalReportVariant();
        assertFalse("largeFile defaults to false", v.getLargeFile());
    }

    @Test
    public void testPartsEmptyByDefault() {
        FinalReportVariant v = new FinalReportVariant();
        assertNotNull("Parts list should not be null", v.getParts());
        assertTrue("Parts list should be empty", v.getParts().isEmpty());
    }

    // --- setBase64Content / getBase64Content: small content path ---

    @Test
    public void testSmallContentStoredDirectly() {
        FinalReportVariant v = new FinalReportVariant();
        v.setBase64Content("smallcontent");

        assertFalse("Small content should not be marked largeFile", v.getLargeFile());
        assertTrue("Parts should be empty for small content", v.getParts().isEmpty());
        assertEquals("smallcontent", v.getBase64Content());
    }

    @Test
    public void testSetNullContent() {
        FinalReportVariant v = new FinalReportVariant();
        v.setBase64Content(null);

        assertFalse("Null content should not set largeFile", v.getLargeFile());
        assertNull("Null content should return null", v.getBase64Content());
    }

    // --- setBase64Content / getBase64Content: large content path ---

    @Test
    public void testLargeContentIsChunked() {
        FinalReportVariant v = new FinalReportVariant();
        v.setBase64Content(buildString(16_000_001));

        assertTrue("Content over 15MB should be marked largeFile", v.getLargeFile());
        assertTrue("Parts should be populated for large content", v.getParts().size() > 0);
    }

    @Test
    public void testLargeContentRoundTrip() {
        FinalReportVariant v = new FinalReportVariant();
        String large = buildString(16_000_001);
        v.setBase64Content(large);

        assertEquals("Round-trip through chunking should return identical content", large, v.getBase64Content());
    }

    @Test
    public void testChunkCountIsCorrect() {
        FinalReportVariant v = new FinalReportVariant();
        v.setBase64Content(buildString(31_000_001)); // ~2 full chunks + remainder

        assertTrue("Two+ chunks should be stored", v.getParts().size() >= 2);
    }

    @Test
    public void testSetBase64ContentClearsPreviousParts() {
        FinalReportVariant v = new FinalReportVariant();
        v.setBase64Content(buildString(16_000_001)); // creates parts
        assertTrue("Setup: should have parts", v.getParts().size() > 0);

        v.setBase64Content("newsmall"); // small re-set should clear
        assertTrue("Parts must be cleared after small re-set", v.getParts().isEmpty());
        assertFalse("largeFile must be false after small re-set", v.getLargeFile());
        assertEquals("newsmall", v.getBase64Content());
    }

    // --- initFromLegacy ---

    @Test
    public void testInitFromLegacy_smallFile() {
        FinalReportVariant v = new FinalReportVariant();
        v.initFromLegacy("legacyb64", false, new ArrayList<>());

        assertFalse("Small legacy should not be marked largeFile", v.getLargeFile());
        assertEquals("legacyb64", v.getBase64Content());
        assertTrue("Parts should be empty", v.getParts().isEmpty());
    }

    @Test
    public void testInitFromLegacy_largeFileAssembledFromParts() {
        FinalReportVariant v = new FinalReportVariant();
        FinalReportPart p0 = new FinalReportPart();
        p0.setIndex(0);
        p0.setBase64Part("AAAA");
        FinalReportPart p1 = new FinalReportPart();
        p1.setIndex(1);
        p1.setBase64Part("BBBB");

        v.initFromLegacy("", true, Arrays.asList(p0, p1));

        assertTrue("Should be marked largeFile", v.getLargeFile());
        assertEquals("Parts should be assembled in index order", "AAAABBBB", v.getBase64Content());
    }

    @Test
    public void testInitFromLegacy_partsOutOfOrderReassembled() {
        FinalReportVariant v = new FinalReportVariant();
        FinalReportPart p0 = new FinalReportPart();
        p0.setIndex(0);
        p0.setBase64Part("FIRST");
        FinalReportPart p1 = new FinalReportPart();
        p1.setIndex(1);
        p1.setBase64Part("SECOND");

        // Supply in reverse order — getBase64Content must sort by index
        v.initFromLegacy("", true, Arrays.asList(p1, p0));

        assertEquals("Parts should be sorted by index before assembly", "FIRSTSECOND", v.getBase64Content());
    }

    @Test
    public void testInitFromLegacy_nullPartsDefaultsToEmptyList() {
        FinalReportVariant v = new FinalReportVariant();
        v.initFromLegacy("content", false, null);

        assertNotNull("Parts must not be null after initFromLegacy(null)", v.getParts());
        assertTrue("Parts should be empty", v.getParts().isEmpty());
    }

    @Test
    public void testInitFromLegacy_nullLargeFileDefaultsFalse() {
        FinalReportVariant v = new FinalReportVariant();
        v.initFromLegacy("content", null, new ArrayList<>());

        assertFalse("Null largeFile should default to false", v.getLargeFile());
        assertEquals("content", v.getBase64Content());
    }

    @Test
    public void testInitFromLegacy_doesNotRechunk() {
        // initFromLegacy must reference the caller's parts list directly rather than
        // re-running the chunking path in setBase64Content (which would allocate new
        // FinalReportPart objects and break the caller's existing references).
        FinalReportVariant v = new FinalReportVariant();
        FinalReportPart original = new FinalReportPart();
        original.setIndex(0);
        original.setBase64Part("ORIG");
        List<FinalReportPart> parts = Arrays.asList(original);

        v.initFromLegacy("", true, parts);

        assertSame("initFromLegacy must use the same part objects, not re-chunk them",
                original, v.getParts().get(0));
    }

    // --- helpers ---

    private String buildString(int length) {
        char[] chars = new char[length];
        Arrays.fill(chars, 'X');
        return new String(chars);
    }
}
